name: create index.html

on:
  push:
    paths:
      - "index.md"

jobs:
  create-index:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install Pandoc
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc

      - name: Create output directory
        run: mkdir -p output

      - name: Converts Markdown to HTML
        uses: jaywcjlove/markdown-to-html-cli@main
        with:
          source: index.md
          output: ./output/index.html
          favicon: favicon.ico
          markdown-style-theme: light
          dark-mode: false
          corners: false

      - name: Upload HTML artifact
        uses: actions/upload-artifact@v6
        with:
          name: website
          path: output/

  deploy:
    needs: create-index
    runs-on: ubuntu-latest

    steps:
      - name: Download HTML artifact
        uses: actions/download-artifact@v6
        with:
          name: website
          path: output/

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: tireschert.ch
          username: pv3o93_gised_link
          password: ${{ secrets.ftp_password }}
          local-dir: output/